### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by mavillan** [bryankim96/ctalearn#12]
Hi,

I'm trying to run your models and reproduce your results, but it wasn't possible because there aren't example datasets in your repository. 

Can you provide links where we can download some simtel or hdf5 files you use to train the models? 

Greetings,
-- mavillan

**Comment by aribrill** [comment]
Thanks for your interest! Please follow the link in the [readme](https://github.com/bryankim96/ctalearn#configuration) to the CTA Machine Learning wiki page for instructions to download the internal CTA MLProto dataset used to produce our results.

Ari
