### ISSUE TITLE
Move open_file and close_file calls outside load_data functions

### ISSUE THREAD

**Issue by bryankim96** [bryankim96/ctalearn#2]
If Dataset.from_generator is changed to support multi-threading like Dataset.map, calls to open HDF5 files should preferably be moved outside of the load_data functions. i.e. all HDF5 files should be opened in advance and the file handles passed into the load_data functions instead of filename strings. This avoids a lot of unnecessary open and close files calls.

On a test of loading 1000 examples from a single HDF5 file with load_data_single_tel_HDF5, moving the file open and closing outside of load_data_single_tel_HDF5 (instead of calling them for each example) reduced runtime by ~30%. Improvement is probably much larger when >>1000 examples are read per HDF5 file.

**Comment by aribrill** [comment]
Closed with commit 8d51872b7ba7a43496786d6046abc4ce14c88a1a
