### ISSUE TITLE
Fix or remove test_metadata.py

### ISSUE THREAD

**Issue by aribrill** [bryankim96/ctalearn#27]
The use case of the script script test_metadata.py is unclear and needs to be clearly defined. 

Assuming it's worth keeping, several problems need to be fixed. As written, sections are missing and it doesn't run. There is a hardcoded path on line 26 that needs to be removed. The name "test_metadata" is ambiguous and the script should be renamed to remove the word "test". It also should be updated to be compatible with the HDF5_data_loader class (see #15).

Alternatively, if the script isn't worth keeping, remove it.

**Comment by bryankim96** [comment]
Completed in 95026d616f1086668e2027bc5531fa997cee9aa6.
