### ISSUE TITLE
Add mapping tables for all telescope types

### ISSUE THREAD

**Issue by aribrill** [bryankim96/ctalearn#9]
At present the only mapping table in image.py from vectors of pixels to the image shape is for the SCT (MSTS). In order to process data for other telescope types, mapping tables for other telescope types must be added. It would make sense to start with square-pixel telescopes, as there isn't yet a standard method for converting hexagonal pixels to a square grid.

**Comment by qi-feng** [comment]
@bryankim96 
I see that in this commit you made changes to generate_table_generic(); in line 392 in the current master branch, you have 
output_dim = self.image_shapes[tel_type][0] 
I had separate dimensions for width and length just in case we want output a rectangular array in the future. Is this something that we'd like to have it capable of? 

https://github.com/bryankim96/ctalearn/commits/cbb7b0cb2448f1426bde5fda0c6485a9b4ed8f9f/ctalearn/image_mapping.py?author=bryankim96

**Comment by qi-feng** [comment]
This issue can now be closed after push 5c866ef5b6ca056f9673c82ada79586873236ecc
